- name: Check clickhouse config,data and logs
  file:
    dest: "{{ item }}"
    owner: clickhouse
    group: clickhouse
    state: directory
  with_items:
    - "{{ clickhouse_path_logdir }}"
    - "{{ clickhouse_path_configdir }}"
    - "{{ clickhouse_path_tmp }}"
    - "{{ clickhouse_path_data }}"
  notify: restart-ch
  become: true

- name: Config | Generate system config
  template:
   src: config.j2
   dest: "{{ clickhouse_path_configdir }}/config.xml"
  notify: restart-ch
  become: true

- name: Config | Generate users config
  template:
   src: users.j2
   dest: "{{ clickhouse_path_configdir }}/users.xml"
  notify: restart-ch
  become: true

- meta: flush_handlers



