- name: Check clickhouse config,data and logs
  file:
    dest: "{{ item }}"
    owner: clickhouse
    group: clickhouse
    state: directory
  with_items:
    - "{{ clickhouse_path_logdir }}"
    - "{{ clickhouse_path_configdir }}"
    - "{{ clickhouse_path_tmp }}"
    - "{{ clickhouse_path_data }}"
  notify: restart-ch
  become: true

- name: Config | Generate system config
  template:
    src: config.j2
    dest: "{{ clickhouse_path_configdir }}/config.xml"
    owner: clickhouse
    group: clickhouse
  notify: restart-ch
  become: true

- name: Config | Generate users config
  template:
    src: users.j2
    dest: "{{ clickhouse_path_configdir }}/users.xml"
    owner: clickhouse
    group: clickhouse
  notify: restart-ch
  become: true

- name: Config | Create conf folder
  file:
    path: "{{ clickhouse_path_configdir }}/conf.d"
    state: directory
    owner: clickhouse
    group: clickhouse
  become: true

- name: Config | Generate remote_servers config
  template:
    src: remote_servers.j2
    dest: "{{ clickhouse_path_configdir }}/conf.d/clickhouse_remote_servers.xml"
    owner: clickhouse
    group: clickhouse
  notify: restart-ch
  become: true
  when: clickhouse_shards is defined 

- name: Config | Generate macros config
  template:
    src: macros.j2
    dest: "{{ clickhouse_path_configdir }}/conf.d/macros.xml"
    owner: clickhouse
    group: clickhouse
    mode: 0644
  notify: restart-ch
  become: true
  when: clickhouse_macros is defined 

- name: Config | Generate zookeeper servers config
  template:
    src: zookeeper-servers.j2
    dest: "{{ clickhouse_path_configdir }}/conf.d/zookeeper-servers.xml"
    owner: clickhouse
    group: clickhouse
    mode: 0644
  notify: restart-ch
  become: true
  when: clickhouse_zookeeper_nodes is defined 

- meta: flush_handlers
