#Main installation actions
#https://clickhouse.yandex/docs/en/getting_started/index.html#installation

- name: Install by APT | Apt-key add repo key
  apt_key:
    keyserver: "{{ clickhouse_repo_keyserver }}"
    id: "{{ clickhouse_repo_key }}"
  become: true

- name: Install by APT | Repo installation
  apt_repository:
    repo: "{{ clickhouse_repo }}"
    state: present
  become: true

- name: Install by APT | Package installation
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ clickhouse_package }}"
  become: true