- name: Requirements check | Check if Clickhouse is installed
  shell: rpm -qa --queryformat '%{NAME}\n'  | sort | grep clickhouse | tr '\n' ' ' |grep -q "{{ clickhouse_package| join(" ")}}"
  register: "{{ clickhouse_rt_is_installed_dict.yum }}"
  ignore_errors: yes
  when: ansible_pkg_mgr == 'yum' and clickhouse_setup == 'package'
  changed_when: False
  check_mode: no

- name: Requirements check | Check if Clickhouse is installed and has required version
  shell: rpm -q --queryformat '%{VERSION}' "{{ item }}"
  register: clickhouse_rt_versions_tmp
  ignore_errors: yes
  when: ansible_pkg_mgr == 'yum' and clickhouse_setup == 'package'
  changed_when: False
  check_mode: no
  with_items: "{{ clickhouse_package }}"