#Main installation actions
#https://clickhouse.yandex/docs/en/getting_started/index.html#installation

- name: Uninstall by APT | Package uninstallation
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items: "{{ clickhouse_package }}"
  become: true

- name: Uninstall by APT | Repo uninstallation
  apt_repository:
    repo: "{{ clickhouse_repo }}"
    state: absent
  become: true

- name: Uninstall by APT | Apt-key remove repo key
  apt_key:
    keyserver: "{{ clickhouse_repo_keyserver }}"
    id: "{{ clickhouse_repo_key }}"
    state: absent
  become: true

- name: Remove clickhouse config,data and logs
  file:
    dest: "{{ item }}"
    state: absent
  with_items:
    - "{{ clickhouse_path_logdir }}"
    - "{{ clickhouse_path_configdir }}"
    - "{{ clickhouse_path_tmp }}"
    - "{{ clickhouse_path_data }}"
  become: true
  when: clickhouse_remove_full|bool
